name: Format

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: dartfmt
      shell: bash -xe {0}
      run: |
        if [ -z $(dartfmt ./ -n) ]; then
          exit 0;
        else
          exit 1;
        fi
